### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Gael-Ro** [valentin-marquez/EasyFX-2.9#1]
Hello! I've tried installing this port for Blender 3.4 and I got this error.
![2023-01-24 21_00_01-Window](https://user-images.githubusercontent.com/123519494/214447965-f61e7122-5c26-46fd-b798-72dbd859feff.png)

**Comment by valentin-marquez** [comment]
it's an error that has to do with the name of the .zip file, I think it's because you downloaded the repository, changed the name of the zip file to "EasyFx.zip" and reinstalled it that should work.

**Comment by Gael-Ro** [comment]
Okay, so I unzipped it, renamed the folder to what it requested- "EasyFX-2", and placed it on the addon folder, installing it manually. It works now, thank you very much!
